name: Show a Nix development environment in action in CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_store_paths:
    name: Display the Nix store paths of installed packages
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Display versions
        run: |
          type python
          type go
          type node
          type terraform
